library(rvest)
url <- 'https://www.99acres.com/search/project/buy/residential/andheri-east-mumbai-andheri-dahisar?search_type=QS&search_location=SH&lstAcn=NPSEARCH&lstAcnId=6984629776344979&src=CLUSTER&preference=S&city=218&res_com=R&locality_array_for_zedo=3230&selected_tab=3&isvoicesearch=N&keyword_suggest=andheri%20(east)%2C%20mumbai%20andheri-dahisar%3B&fullSelectedSuggestions=andheri%20(east)%2C%20mumbai%20andheri-dahisar&strEntityMap=W3sidHlwZSI6ImxvY2FsaXR5In0seyIxIjpbImFuZGhlcmkgKGVhc3QpLCBtdW1iYWkgYW5kaGVyaS1kYWhpc2FyIiwiQ0lUWV8yMTgsIExPQ0FMSVRZXzMyMzAsIFBSRUZFUkVOQ0VfUywgUkVTQ09NX1IiXX1d&texttypedtillsuggestion=andheri%20mumbai&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_218%2C%20LOCALITY_3230%2C%20PREFERENCE_S%2C%20RESCOM_R&searchform=1&locality=3230&price_min=null&price_max=null'
webpage <- read_html(url)
description <- html_nodes(webpage,'.npt_titl_desc')
description <- html_text(description)
description <- as.list(description)
BHK <- html_nodes(webpage,'._bedrm1')
BHK <- html_text(BHK)
BHK <- as.list(BHK)
price <- html_nodes(webpage,'._price')
price <- html_text(price)
price <- as.list(price)
status <- html_nodes(webpage,'._poss')
status <- html_text(status)
status <- as.list(status)
description <- as.data.frame(description)
BHK <- as.data.frame(BHK)
price <- as.data.frame(price)
status <- as.data.frame(status)
Andheri <- merge.data.frame(description,price,status,BHK,by=intersect(names(description),names(price),names(status),names(BHK)))
area <- html_nodes(webpage,'._bedrm1+ .npsrp_tip')
